environment:
  PYTHON: "C:\\Python36-x64"
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    ARCH: x86_64
    DIR: "C:\\issues\\conan_bullet_1"

matrix:
  fast_finish: false

clone_folder: C:\issues

build_script:
  - "%DIR%\\run.py"
