environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  PYTHON: "C:\\Python36-x64"
  CMAKE_GENERATOR: Visual Studio 15 2017 Win64
  matrix:
  - DIR: "C:\\issues\\conan_bullet_1"
  - DIR: "C:\\issues\\conan_bullet_2"
  - DIR: "C:\\issues\\conan_ffmpeg_1"

matrix:
  fast_finish: false

clone_folder: C:\issues

build_script:
  - "%DIR%\\run.py"
