cache:
  - C:\Users\appveyor\.conan -> .cache
  - C:\.conan -> .cache

configuration:
#  - Debug
  - Release

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  PYTHON: "C:\\Python36-x64"
  CMAKE_GENERATOR: Visual Studio 15 2017 Win64
  matrix:
  - DIR: "C:\\issues\\conan_boost_test_2b"
  - DIR: "C:\\issues\\conan_boost_test_1"
  - DIR: "C:\\issues\\conan_boost_test_2"
  - DIR: "C:\\issues\\conan_boost_program_options_1"
  - DIR: "C:\\issues\\conan_ffmpeg_2"
  - DIR: "C:\\issues\\conan_ffmpeg_1"
  - DIR: "C:\\issues\\conan_bullet_1"

matrix:
  fast_finish: false

clone_folder: C:\issues

build_script:
  - "%DIR%\\run.py"
