language: cpp

os: linux

sudo: required

matrix:
  include:
  - env: DIR="conan_boost_test_1"
  - env: DIR="conan_boost_test_2"
  - env: DIR="conan_openal_1"

script:
  - pyenv shell 3.6
  - "$TRAVIS_BUILD_DIR/$DIR/run.py"
