name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { os: windows-latest }
          - { os: macos-latest }
          - { os: ubuntu-latest }
    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      if: ${{ matrix.platform.os == 'windows-latest' }}
      with:
        arch: x64
    - name: Set up SDL
      id: sdl
      uses: madebr/setup-sdl@master
      with:
        version: 3-head
    - uses: actions/checkout@v3
    - name: Configure (CMake)
      run: |
        cmake -S . -B build
    - name: Build (CMake)
      run: |
        cmake --build build

