name: 'Build'

on: [push, pull_request]

jobs:
  xxx:
    name: 'xxx'
    runs-on: 'macos-latest'
    strategy:
      fail-fast: false
      matrix:
#        cmake-version: [ '3.0', '3.2', '3.4', '3.6', '3.8', '3.10', '3.12', '3.14', '3.16', '3.18', '3.20', '3.22', '3.24', '3.26', '3.27', '3.28', '3.30', '3.31']
        cmake-version: [ '3.12', '3.14', '3.16', '3.18', '3.20', '3.22', '3.24', '3.26', '3.27', '3.28', '3.30', '3.31']
        patch: [true, false]
    steps:
      - uses: actions/checkout@v4
      - name: Download SDL3 dmg
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh -R libsdl-org/SDL release download release-3.2.0 -p SDL3-3.2.0.dmg
          hdiutil attach SDL3-3.2.0.dmg
          mkdir /tmp/SDL3
          cp -r /Volumes/SDL3/* /tmp/SDL3
      - name: Patch SDL3 CMake configuration file
        if: ${{ matrix.patch }}
        run: |
          sed -i -E 's#IMPORTED_LOCATION "[$][{]_sdl3_framework_path[}]"#IMPORTED_LOCATION "${_sdl3_framework_path}/SDL3"#' /tmp/SDL3/share/cmake/SDL3/SDL3Config.cmake
      - name: cat SDL3Config.cmake
        run: |
          cat /tmp/SDL3/share/cmake/SDL3/SDL3Config.cmake
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ matrix.cmake-version }}
      - name: 'Set up ninja'
        uses: ./.github/actions/setup-ninja
      - name: Configure (CMake)
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=/tmp/SDL3 -DTEST_STATIC=OFF -DTEST_TEST=OFF -DTEST_FULL=OFF -GNinja
      - name: Build (CMake)
        run: |
          ninja -C build -v
      - name: Run cli-shared
        run: |
          build/cli-shared
