name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ amtrix.platform.os }}
#    runs-on: ${{ matrix.platform.os }}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: 'windows: mingw64',   os: 'windows-latest', shell: 'msys2 {0}',   msys2: true,  msystem: 'mingw64', msys-env: 'mingw-w64-x86_64' }
        - { name: 'windows: clang32', os: windows-latest,     shell: 'msys2 {0}',   msys2: true,  msystem: 'clang32', msys-env: 'mingw-w64-clang-i686' }
    steps:
#    - uses: ilammy/msvc-dev-cmd@v1
#      if: ${{ matrix.platform.msvc }}
#      with:
#        arch: ${{ matrix.platform.msvc_arch }}
    - name: Set up MSYS2
      if: ${{ matrix.platform.msys2 }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.platform.msystem }}
        install: >-
          ${{ matrix.platform.msys-env }}-cc
          ${{ matrix.platform.msys-env }}-cmake
          ${{ matrix.platform.msys-env }}-ninja
          ${{ matrix.platform.msys-env }}-pkg-config
    - uses: actions/checkout@v3
    - name: Set up SDL2
      id: sdl2
      uses: madebr/setup-sdl@experimental
      with:
        version: 2-head
        shell: ${{ matrix.platform.shell }}
        cmake-toolchain-file: ${{ matrix.platform.cmake-toolchain-file }}
        install-linux-dependencies: true
    - name: Set up SDL3
      id: sdl3
      uses: madebr/setup-sdl@experimental
      with:
        version: 3-head
        shell: ${{ matrix.platform.shell }}
        cmake-toolchain-file: ${{ matrix.platform.cmake-toolchain-file }}
        install-linux-dependencies: true
    - name: Configure (CMake)
      run: |
        cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${{ matrix.platform.cmake-toolchain-file }}
    - name: Build (CMake)
      run: |
        cmake --build build
    - name: Stress test main_sdl2
      run: |
        set -eu
        for i in {1..200}; do (time build/main_sdl2 2>/dev/null) 2>&1 | grep real | awk '{print $2}'; done
    - name: Stress test main_sdl2
      run: |
        set -eu
        for i in {1..200}; do (time build/main_sdl3 2>/dev/null) 2>&1 | grep real | awk '{print $2}'; done

