name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
#    runs-on: ${{ matrix.platform.os }}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: 'windows: mingw64',   os: 'windows-latest', shell: 'msys2 {0}',   msys2: true,  msystem: 'mingw64', msys-env: 'mingw-w64-x86_64' }
        - { name: 'windows: clang32',   os: 'windows-latest', shell: 'msys2 {0}',   msys2: true,  msystem: 'clang32', msys-env: 'mingw-w64-clang-i686' }
    steps:
#    - uses: ilammy/msvc-dev-cmd@v1
#      if: ${{ matrix.platform.msvc }}
#      with:
#        arch: ${{ matrix.platform.msvc_arch }}
    - name: Set up MSYS2
      if: ${{ matrix.platform.msys2 }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.platform.msystem }}
        install: >-
          ${{ matrix.platform.msys-env }}-cc
          ${{ matrix.platform.msys-env }}-cmake
          ${{ matrix.platform.msys-env }}-ninja
          ${{ matrix.platform.msys-env }}-pkg-config
    - uses: actions/checkout@v3
#    - name: Set up SDL2
#      id: sdl2
#      uses: madebr/setup-sdl@experimental
#      with:
#        version: 2-latest
#        shell: ${{ matrix.platform.shell }}
#        cmake-toolchain-file: ${{ matrix.platform.cmake-toolchain-file }}
#        install-linux-dependencies: true
#        sdl-test: true
    - name: Set up SDL3
      id: sdl3
      uses: madebr/setup-sdl@experimental
      with:
        build-type: Release
        version: b1a0bc3fb0ad2198500cbddc2e8c73d8ec39de31
        shell: ${{ matrix.platform.shell }}
        cmake-toolchain-file: ${{ matrix.platform.cmake-toolchain-file }}
        install-linux-dependencies: true
        sdl-test: true
        add-to-environment: true
    - name: Configure (CMake)
      run: |
        cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${{ matrix.platform.cmake-toolchain-file }} -DCMAKE_BUID_TYPE=Release -GNinja
    - name: Build (CMake)
      run: |
        cmake --build build
    - name: test1
      continue-on-error: true
      run: |
        export PATH=$(cygpath "${{env.SDL3_ROOT}}/bin"):$PATH
        echo "PATH=$PATH"
        cd build
        ctest -V
#    - name: test2
#      continue-on-error: true
#      run: |
#        export PATH=$(cygpath "${{env.SDL3_ROOT}}/bin"):$PATH
#        echo "PATH=$PATH"
#        cd build
#        ctest -V
#    - name: test3
#      continue-on-error: true
#      run: |
#        export PATH=$(cygpath "${{env.SDL3_ROOT}}/bin"):$PATH
#        echo "PATH=$PATH"
#        cd build
#        ctest -V
#    - name: repeated testlocale
#      continue-on-error: true
#      run: |
#        export SDL_AUDIO_DRIVER=dummy
#        export SDL_VIDEO_DRIVER=dummy
#        export PATH=$(cygpath "${{env.SDL3_ROOT}}/bin"):$PATH
#        echo "PATH=$PATH"
#        build/sdl3_testlocale
#        for i in {1..100}; do (time build/sdl3_testlocale 2>/dev/null) 2>&1 | grep real | awk '{print $2}'; done
#    - name: repeated testkeys
#      continue-on-error: true
#      run: |
#        export SDL_AUDIO_DRIVER=dummy
#        export SDL_VIDEO_DRIVER=dummy
#        export PATH=$(cygpath "${{env.SDL3_ROOT}}/bin"):$PATH
#        echo "PATH=$PATH"
#        build/sdl3_testkeys
#        for i in {1..100}; do (time build/sdl3_testkeys 2>/dev/null) 2>&1 | grep real | awk '{print $2}'; done
#    - name: repeated testkeys + testlocale
#      continue-on-error: true
#      run: |
#        export SDL_AUDIO_DRIVER=dummy
#        export SDL_VIDEO_DRIVER=dummy
#        export PATH=$(cygpath "${{env.SDL3_ROOT}}/bin"):$PATH
#        echo "PATH=$PATH"
#        sh -c "build/sdl3_testkeys; build/sdl3_testlocale"
#        for i in {1..100}; do (time sh -c "build/sdl3_testkeys;build/sdl3_testlocale" 2>/dev/null) 2>&1 | grep real | awk '{print $2}'; done
    - name: repeated everything
      continue-on-error: true
      run: |
        export SDL_AUDIO_DRIVER=dummy
        export SDL_VIDEO_DRIVER=dummy
        export PATH=$(cygpath "${{env.SDL3_ROOT}}/bin"):$PATH
        echo "PATH=$PATH"
        python runall.py
