name: 'Build'

on: [push, pull_request]

jobs:
  xxx:
    name: 'xxx'
    runs-on: 'macos-latest'
    strategy:
      fail-fast: false
      matrix:
        cmake-version: [ '3.0', '3.2', '3.4', '3.6', '3.8', '3.10', '3.12', '3.14', '3.16', '3.18', '3.20', '3.22', '3.24', '3.26', '3.28', '3.30', '3.31']
    steps:
      - uses: actions/checkout@v4
      - name: Download SDL3 dmg
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh -R libsdl-org/SDL release download release-3.2.0 -p SDL3-3.2.0.dmg
          hdiutil attach SDL3-3.2.0.dmg
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ matrix.cmake-version }}
      - name: Configure (CMake)
        run: |
          cmake -B build -DCMAKE_PREFIX_PATH=/Volumes/SDL3 -DTEST_STATIC=OFF -DTEST_TEST=OFF -DTEST_FULL=OFF
      - name: Build (CMake)
        run: |
          cmake --build build
