name: Build

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SDL
      id: sdl
      uses: madebr/setup-sdl@master
      with:
        version: 3-head
    - uses: actions/checkout@v3
    - name: Configure (CMake)
      run: |
      	cmake -S . -B build -DCMAKE_PREFIX_PATH=${{ steps.sdl.outputs.prefix }}
    - name: Build (CMake)
      run: |
        cmake --build build

